packages:
  - apps/*
  - tooling/*
  - packages/*

catalog:
  eslint: ^9.29.0
  prettier: ^3.5.3
  typescript: ^5.8.2
  tailwindcss: ^3.4.4
  tailwindcss-animate: ^1.0.7
  '@tailwindcss/typography': ^0.5.16
  tailwind-merge: ^2.3.0
  postcss: ^8.5.3
  '@types/node': ^22.13.11
  autoprefixer: ^10.4.19
  sass: ^1.77.8
  rimraf: ^6.0.1

  zod: ^3.24.2
  zustand: ^5.0.3
  libphonenumber-js: ^1.11.17
  dayjs: ^1.11.11
  date-fns: ^3.6.0
  slugify: ^1.6.6
  html-react-parser: ^5.2.2

  '@tanstack/react-query': ^5.70.0
  '@tanstack/react-query-persist-client': ^5.70.0
  '@tanstack/react-query-devtools': ^5.70.0

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.12
    '@types/react-dom': ^18.3.5
